### ISSUE TITLE
More detail on interface size

### ISSUE THREAD

**Issue by munificent** [nex3/dep-import-when#1]
Here's some notes I wrote up a while back about how an interface-only library affects a program that doesn't use it. I did some comparisons of four programs:
- **nothing:** A hello world that does not import "dart:html" at all.
- **normal:** Like the previous but imports the stub "dart:html" generated directly by Natalie's program.
- **no_strings:** Like the previous but all UnsupportedError error messages are replaced by "".
- **no_meta:** Like the previous and also removes all metadata annotations (since those are used almost entirely for docs).

Here are the generated snapshot sizes:

```
nothing:        578 bytes
normal:     776,887 bytes
no_strings: 609,079 bytes
no_meta:    357,448 bytes
```

Here's timings running these programs on my Mac laptop (ReleaseIA32) directly from source:

```
nothing:    0m0.058s
normal:     0m0.136s  +78ms
no_strings: 0m0.127s  +69ms
no_meta:    0m0.098s  +40ms
```

And then when previously compiled to a snapshot:

```
nothing:    0m0.058s
normal:     0m0.076s  +18ms
no_strings: 0m0.070s  +12ms
no_meta:    0m0.066s  + 8ms
```

Of course, there's no tree-shaking going on here. These numbers are what a developer would experience when iterating on their app. Assuming they deploy an app using something like dart2dart, this gets better. Using dart2js output size as a rough approximation of that, here's what I get:

```
nothing:    14,097 bytes
normal:     14,172 bytes +79 bytes
no_strings: 14,187 bytes +90 bytes
no_meta:    14,181 bytes +84 bytes
```

Which is what you'd expect. Since the program doesn't actually use anything from "dart:html" it's all completely tree-shaken out.

**Comment by nex3** [comment]
It's worth noting that my old stub handler was suboptimal in some cases—in particular, it left in a lot of unnecessary private members. I hacked up some patches for it locally when writing this up, which is what I used to generate the files in this repo, but the version you ran probable included more code than necessary.

Anyway, thanks for writing this up. When you have a sec, could you make a pull request to put this information into a file in the repo and link it from the proposal?
