### ISSUE TITLE
Are collisions allowed?

### ISSUE THREAD

**Issue by munificent** [nex3/dep-import-when#4]
Can I do something like:

``` dart
import 'html5lib_element.dart' when 'dart:io';
import 'dart:html' when 'dart:html';

class MyElement extends Element {}
```

And have it get the right base class at runtime based on which library was imported?

CC @jmesserly

**Comment by jmesserly** [comment]
I see this is closed, but it doesn't seem to address the package:html Element use case at all? Unless I'm missing something?
